name: Ziggeo Integration Tests
on: [ push, pull_request ]

jobs:
  drive_android:
    runs-on: macos-latest
    
    strategy:
      matrix:
        api-level: [ 23 ]
        target: [ default ]
    steps:
      - uses: actions/checkout@v3
      - name: Set default Xamarin SDK versions
        run: |
          $VM_ASSETS/select-xamarin-sdk-v2.sh --mono=6.12.0 --android=12.0.0.3

      - name: Setup .NET Core SDK 6.0.x
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
        with:
          nuget-version: '5.x'
      
      - name: Install dependencies
        run: dotnet restore

      - name: Install test dependencies
        run: dotnet restore /Users/runner/work/Xamarin-SDK/Xamarin-SDK/Ziggeo.Xamarin.NetStandard/Ziggeo.Xamarin.NetStandard.csproj

      - name: Nuget Instal
        run: nuget install

      - name: Build
        run: msbuild /Users/runner/work/Xamarin-SDK/Xamarin-SDK/Ziggeo.Xamarin.NetStandard/Ziggeo.Xamarin.NetStandard.csproj /t:Clean,Build,Pack 

      - name: Creation Nugget package
        run: dotnet pack /Users/runner/work/Xamarin-SDK/Xamarin-SDK/Ziggeo.Xamarin.NetStandard/Ziggeo.Xamarin.NetStandard.csproj --configuration Release -o .
        
      - name: Publish nuget package
        run: dotnet nuget push Ziggeo.XamarinSDK.Netstandard.1.3.14.nupkg  -k ${{ secrets.UPDATE_TOKIN }} -s https://api.nuget.org/v3/index.json -t 360 --skip-duplicate
    