name: Ziggeo Integration Tests
on: [ push, pull_request ]

jobs:
  drive_android:
    runs-on: macos-latest
    
    strategy:
      matrix:
        api-level: [ 23 ]
        target: [ default ]
    steps:
      - uses: actions/checkout@v3
      - name: Set default Xamarin SDK versions
        run: |
          $VM_ASSETS/select-xamarin-sdk-v2.sh --mono=6.12.0 --android=12.0.0.3

      - name: Setup .NET Core SDK 6.0.x
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
        
#        //todo
#      - name: Get Build Version
#        run: |
#            Import-Module .\build\GetBuildVersion.psm1
#            Write-Host $Env:GITHUB_REF
#            $version = GetBuildVersion -VersionString $Env:GITHUB_REF
#            echo "BUILD_VERSION=$version" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
#        shell: pwsh

      - name: Nuget pack
        run: nuget pack

      - name: Publish nuget package
        run: dotnet nuget push Ziggeo.XamarinSDK.Netstandard.1.3.10.nupkg  --api-key ${{ secrets.NUGET_TOKEN }} --source https://api.nuget.org/v3/index.json --timeout 360
    